import { Inter } from "next/font/google";
import "./globals.scss";
import Headers from "./Headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ko-play",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <Headers />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
